import { Onest } from 'next/font/google';
import './globals.css';

import type { Metadata } from 'next';

// Font
const onest = Onest({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${onest.className} text-sm antialiased`}>
        {children}
      </body>
    </html>
  );
}
